sd(c(5,8,12))
which.min(c(4,1,6))
sqrt(9)
abs(-9)
SquareRoot2 = sqrt(2)
SquareRoot2
Country <- c("Brazil", "China", "India", "Switzerland", "USA")
LifeExpectancy <- c(74,76,65,83,79)
seq(0,100,2)
CountryData = data.frame(Country, LifeExpectancy)
CountryData$Population <- c(199000, 1390000, 1240000, 7997, 318000)
AllCountryData = rbind(CountryData, NewCountryData)
setwd("C:/Users/Y.SAHITH/Desktop")
getwd()
WHO <- read.csv("WHO.csv")
str(WHO)
summary(WHO)
WHO_Europe <- subset(WHO, Region == "Europe")
write.csv(WHO_Europe, "WHO_Europe.csv")
ls()
WHO$Under15
mean(WHO$Under15)
sd(WHO$Under15)
which.min(WHO$Under15)
WHO$Country[86]
which.max(WHO$Under15)
plot(WHO$GNI, WHO$FertilityRate)
Outliers <- subset(WHO, GNI > 10000 & FertilityRate > 2.5)
nrow(Outliers)
Outliers[c("Country", "GNI", "FertilityRate")]
WHO$Country[which.max(WHO$LiteracyRate)]
hist(WHO$CellularSubscribers)
boxplot(WHO$LifeExpectancy ~ WHO$Region, xlab="", ylab="Life Expectancy", main="Life Expectancy of countries by region")
table(WHO$Region)
tapply(WHO$Over60, WHO$Region, mean)
tapply(WHO$LiteracyRate, WHO$Region, min, na.rm=TRUE)
which.min(tapply(WHO$ChildMortality, WHO$Region, mean))